{
 "title": "FortiNET",
 "description": "A Dashboard for the Prometheus fortigate_exporter",
 "tags": [
  "prometheus",
  "fortigate"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "firewall", "query": "fortigate_version_info" },
   {
    "name": "scope",
    "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "vdom",
    "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "label_values(fortigate_interface_link_up{instance=\"[[firewall]]\"}, name)"
   },
   {
    "name": "phase1",
    "query": "fortigate_ipsec_tunnel_up{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "phase2",
    "query": "fortigate_ipsec_tunnel_up{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "monitor",
    "query": "fortigate_link_status_change_time_seconds{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "sdwan",
    "query": "fortigate_virtual_wan_status{instance=~\"[[firewall]]\"}"
   },
   {
    "name": "certificate",
    "query": {
     "query": "fortigate_certificate_info{instance=~\"[[firewall]]\"}"
    }
   },
   {
    "name": "fortiswitch",
    "query": {
     "query": "query_result(fortigate_managed_switch_port_info{instance=~\"[[firewall]]\"})"
    }
   },
   {
    "name": "mac_address",
    "label": "Wifi Client",
    "query": {
     "query": "query_result(fortigate_wifi_client_info{instance=~\"[[firewall]]\"})"
    }
   },
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fortigate_cpu_usage_ratio{instance=~\"[[firewall]]\"} *100",
     "legendFormat": "CPU{{processor}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fortigate_version_info{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fortigate_memory_usage_ratio{instance=~\"[[firewall]]\"} * 100"
    }
   ]
  },
  {
   "title": "Current Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fortigate_time_seconds{instance=~\"[[firewall]]\"} * 1000"
    }
   ]
  },
  {
   "title": "Up since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fortigate_last_reboot_seconds{instance=~\"[[firewall]]\"} * 1000"
    }
   ]
  },
  {
   "title": "VDOM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fortigate_license_vdom_usage{instance=~\"[[firewall]]\"}",
     "legendFormat": "VDOMs"
    },
    {
     "expr": "fortigate_license_vdom_max\r{instance=~\"[[firewall]]\"}",
     "legendFormat": "VDOM Max"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fortigate_current_sessions{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{protocol}} Sessions"
    }
   ]
  },
  {
   "title": "VPN Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  fortigate_ipsec_tunnel_connections_up{\n    instance=~\"[[firewall]]\",\n    tunnel=~\"(fct1|fct2).*\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Node Serial",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fortigate_version_info{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{serial}}"
    }
   ]
  },
  {
   "title": "HA Members (CPU/Mem/Role)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fortigate_ha_member_cpu_usage_ratio{instance=~\"[[firewall]]\"} * 100",
     "legendFormat": "{{hostname}} CPU"
    },
    {
     "expr": "fortigate_ha_member_memory_usage_ratio{instance=~\"[[firewall]]\"} * 100",
     "legendFormat": "{{hostname}} Mem"
    },
    {
     "expr": "fortigate_ha_member_has_role{instance=~\"[[firewall]]\",role=\"root_master\"}",
     "legendFormat": "{{serial}} master"
    }
   ]
  },
  { "title": "Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "[[interface]] Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 19 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(fortigate_interface_receive_bytes_total{instance=\"[[firewall]]\",name=~\"[[interface]]\"}[1m]) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(fortigate_interface_transmit_bytes_total{instance=\"[[firewall]]\",name=~\"[[interface]]\"}[1m]) * 8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Interface status",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "fortigate_interface_speed_bps{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(fortigate_interface_transmit_packets_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[1m])",
     "legendFormat": "[[interface]] transmit"
    },
    {
     "expr": "irate(fortigate_interface_receive_packets_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[1m])",
     "legendFormat": "[[interface]] receive"
    }
   ]
  },
  {
   "title": "[[interface]] Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fortigate_interface_transmit_errors_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[10m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(fortigate_interface_receive_errors_total{instance=~\"[[firewall]]\",name=~\"[[interface]]\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fortianalyzer Queue Connected",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_log_fortianalyzer_queue_connections{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fortianalyzer Logs Received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 5, "y": 15 },
     "targets": [
      {
       "expr": "fortigate_log_fortianalyzer_logs_received{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Log Disk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9220 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fortigate_log_disk_total_bytes{instance=~\"[[firewall]]\"}",
       "legendFormat": "Total: "
      },
      {
       "expr": "fortigate_log_disk_used_bytes{instance=~\"[[firewall]]\"} ",
       "legendFormat": "Used: "
      }
     ]
    },
    {
     "title": "Fortianalyzer Queue Logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 5, "y": 9220 },
     "targets": [
      {
       "expr": "fortigate_log_fortianalyzer_queue_logs{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FortiSwitch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "fortigate_managed_switch_info{instance=~\"[[firewall]]\", switch_name=~\"$fortiswitch\"}",
       "legendFormat": "{{switch_name}} - {{state}}/{{status}} - {{os_version}}"
      }
     ]
    },
    {
     "title": "Interface status",
     "type": "table",
     "gridPos": { "h": 13, "w": 13, "x": 0, "y": 5647 },
     "targets": [
      {
       "expr": "fortigate_managed_switch_port_info{instance=~\"[[firewall]]\", switch_name=~\"$fortiswitch\"}",
       "legendFormat": "{{port}}"
      }
     ]
    },
    {
     "title": "Poe Watt",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 13, "y": 5647 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "fortigate_managed_switch_port_power_watt{instance=~\"[[firewall]]\", switch_name=~\"$fortiswitch\"}",
       "legendFormat": "{{port}}"
      }
     ]
    },
    {
     "title": "PoE Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 20, "y": 5647 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "fortigate_managed_switch_port_power_watt{instance=~\"[[firewall]]\", switch_name=~\"$fortiswitch\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "PoE Budget",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 20, "y": 5650 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_managed_switch_max_poe_budget_watt{instance=~\"[[firewall]]\", switch_name=~\"$fortiswitch\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Policies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6546 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(fortigate_policy_active_sessions{instance=~\"[[firewall]]\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Policy Hit Cound Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6551 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(fortigate_policy_hit_count_total{instance=~\"[[firewall]]\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Policy Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6556 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(fortigate_policy_bytes_total{instance=~\"[[firewall]]\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Policy Packets Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6561 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(fortigate_policy_packets_total{instance=~\"[[firewall]]\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "VPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Client VPN Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  fortigate_ipsec_tunnel_connections_up{\n    instance=~\"[[firewall]]\",\n    tunnel=~\"(fct1|fct2).*\"\n  }\n)",
     "legendFormat": "Client VPN connections"
    }
   ]
  },
  {
   "title": "IPsec VPN status",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 106 },
   "targets": [
    {
     "expr": "fortigate_ipsec_tunnel_up{instance=\"[[firewall]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Firewall Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 98 },
   "targets": [
    {
     "expr": "fortigate_user_firewall_info{instance=~\"[[firewall]]\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "[[phase2]] Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 102 },
   "repeat": "phase2",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(fortigate_ipsec_tunnel_receive_bytes_total{instance=\"[[firewall]]\",parent=~\"[[phase1]]\",name=~\"[[phase2]]\"}[1m]) * 8",
     "legendFormat": "{{name}} receive"
    },
    {
     "expr": "rate(fortigate_ipsec_tunnel_receive_bytes_total{instance=\"[[firewall]]\",parent=~\"[[phase1]]\",name=~\"[[phase2]]\"}[1m]) * 8\r",
     "legendFormat": "{{name}} transmit"
    }
   ]
  },
  {
   "title": "SD-WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 277 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual WAN Status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8315 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_status{instance=~\"[[firewall]]\", state=\"up\"} != 0\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Latency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8315 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_latency_seconds{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Sent / Received Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 8315 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_packet_sent_total{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}} sent"
      },
      {
       "expr": "fortigate_virtual_wan_packet_received_total{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{interface}} received"
      }
     ]
    },
    {
     "title": "[[sdwan]] State Change",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8352 },
     "repeat": "sdwan",
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_status_change_time_seconds{instance=~\"[[firewall]]\",interface=\"[[sdwan]]\"} *1000",
       "legendFormat": "{{sdwan}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Jitter",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8352 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_latency_jitter_seconds{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 8352 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_active_sessions{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Virtual WAN Packet Loss",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8357 },
     "targets": [
      {
       "expr": "fortigate_virtual_wan_packet_loss_ratio{instance=~\"[[firewall]]\"}\r",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "[[sdwan]] Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 8357 },
     "targets": [
      {
       "expr": "irate(fortigate_virtual_wan_bandwidth_tx_byte_per_second{instance=\"[[firewall]]\",interface=~\"[[sdwan]]\"}[1m]) * 8",
       "legendFormat": "{{interface}} TX"
      },
      {
       "expr": "irate(fortigate_virtual_wan_bandwidth_rx_byte_per_second{instance=\"[[firewall]]\",interface=~\"[[sdwan]]\"}[1m]) * 8\r",
       "legendFormat": "{{interface}} RX"
      }
     ]
    }
   ]
  },
  {
   "title": "FortiWifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 278 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mac to Hostname where available",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8316 },
     "targets": [
      {
       "expr": "fortigate_wifi_client_info{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "APs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8321 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_wifi_access_points{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Clients per AP",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 11, "y": 8321 },
     "targets": [
      {
       "expr": "sum(fortigate_wifi_managed_ap_radio_client_count{instance=~\"[[firewall]]\"}) by (ap_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 8326 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fortigate_wifi_fabric_clients{instance=~\"[[firewall]]\"}",
       "legendFormat": "Clients"
      }
     ]
    },
    {
     "title": "Client Noise",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 11, "y": 8326 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "fortigate_wifi_client_signal_strength_dBm{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "Signal"
      },
      {
       "expr": "fortigate_wifi_client_signal_noise_dBm{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "Noise"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 18, "w": 11, "x": 0, "y": 8330 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fortigate_wifi_managed_ap_info{instance=~\"[[firewall]]\"}",
       "legendFormat": "{{ap_name}} - {{os_version}}"
      }
     ]
    },
    {
     "title": "Data Rate/TX/RX",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 11, "y": 8330 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fortigate_wifi_client_data_rate_bps{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "Rate"
      },
      {
       "expr": "fortigate_wifi_client_bandwidth_tx_bps{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "TX"
      },
      {
       "expr": "fortigate_wifi_client_bandwidth_rx_bps{instance=~\"[[firewall]]\", mac=\"$mac_address\"}",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "AP CPU",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 11, "y": 8335 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "fortigate_wifi_managed_ap_cpu_usage_ratio{instance=~\"[[firewall]]\"} *100",
       "legendFormat": "{{ap_name}}"
      }
     ]
    },
    {
     "title": "AP Mem",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 11, "y": 8340 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fortigate_wifi_managed_ap_memory_bytes_total{instance=~\"[[firewall]]\"} *10000",
       "legendFormat": "{{ap_name}} Total"
      },
      {
       "expr": "fortigate_wifi_managed_ap_memory_free_bytes{instance=~\"[[firewall]]\"} *10000",
       "legendFormat": "{{ap_name}} Free"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate expiry date",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9844 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fortigate_certificate_valid_to_seconds{instance=~\"[[firewall]]\",scope=~\"[[scope]]\",name=~\"[[certificate]]\"} *1000"
      }
     ]
    }
   ]
  }
 ]
}